//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gift_Card
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_description { get; set; }
        public byte[] p_img { get; set; }
        public Nullable<int> p_price { get; set; }
        public string p_img_type { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<System.DateTime> i_date { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
